encoding: UTF-8
title: dxruby_sdl
email: kouji.takao+smalruby@gmail.com
description: >-
  DXRuby on SDL/Ruby
baseurl: "/dxruby_sdl"
url: http://smalruby.jp
github_username: smalruby
show_downloads: false

markdown: kramdown
future: true
jailed: false
gfm_quirks: paragraph_end

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
